import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  containerView: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingBottom: 70,
    justifyContent: 'space-between',
  },

  logoView: {
    flexDirection: 'row',
  },
  thumnailStyle: {
    resizeMode: 'contain',
    marginTop: 80,
    marginBottom: 30,
    width: '30%',
    height: 130,
    borderRadius: 2,
    alignSelf: 'baseline',
  },
  loginBtn: {
    width: '88%',
    alignSelf: 'center',
    backgroundColor: '#cc0000',
    borderRadius: 10,
    minHeight: 40,
    justifyContent: 'center',
    marginVertical: 50,
  },
  loginText: {
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    width: '100%',
    fontSize: 18,
    fontFamily: 'ldfcomicsans',
    textTransform: 'capitalize',
  },
  inputStyle: {
    color: '#000',
    backgroundColor: 'transparent',
    justifyContent: 'space-between',

    fontSize: 14,
    borderColor: '#53607d',
    width: '100%',
    fontFamily: 'ldfcomicsans',
    paddingTop: 10,
  },
  inputContainer: {
    width: '87%',
    margin: 5,
  },
  forgotCont: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 10,
  },
  forgotPassword: {
    color: '#4c76be',
    fontSize: 12,
    fontWeight: 'bold',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    textAlign: 'right',
    width: '44%',
  },
  login: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 10,
  },
  signUP: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#4c76be',
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    textAlign: 'left',
    width: '44%',
  },

  checkboxContainer: {
    width: '100%',
    // backgroundColor: 'blue',
    // alignSelf: 'flex-start',
    // marginLeft: 16,
    // justifyContent: 'flex-start',
    // height: 55,
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 4,
  },
  checkbox: {
    backgroundColor: '#fff',
    width: 20,
    height: 22,
    borderRadius: 3,
    borderColor: '#777777',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
  },
  label: {
    backgroundColor: '#fff',
    // color: 'red',
    marginLeft: -12,
    color: 'grey',
  },
  modal: {
    flex: 1,
    justifyContent: 'flex-end',
    margin: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainer: {
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '600',
  },
  modalText: {
    fontSize: 18,
    color: '#555',
    marginTop: 14,
    textAlign: 'center',
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#000',
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
});

export default styles;
