import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderRadius: 5,
    margin: 10,
    // backgroundColor: 'red',
    backgroundColor: '#fff',
    alignItems: 'center',
    // minHeight: 250,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },

  itemContainerStyle: {
    flexDirection: 'row',
    // paddingHorizontal: 8,
    // backgroundColor: 'red',
    marginVertical: 2,
    // marginHorizontal: 4,
    // flex: 1,
    // flexWrap: 'wrap',
    // justifyContent: 'center',
    alignItems: 'center',
    // marginVertical: 4,
  },

  // ItemNameLableStyle: {
  //   color: '#000',
  //   fontSize: 12,
  //   // fontWeight: 'bold',
  //   marginHorizontal: 4,
  // },
  // ItemPriceLableStyle: {
  //   color: 'gray',
  //   fontSize: 12,
  //   marginHorizontal: 4,
  // },
  // bottomDetails: {
  //   width: '95%',
  //   flex: 1,
  //   paddingVertical: 8,
  //   paddingHorizontal: 4,
  //   backgroundColor: '#fff',
  //   // flexDirection: 'row',
  //   justifyContent: 'center',
  //   // alignItems: 'center',
  // },
  iconsView: {
    height: 50,
    backgroundColor: 'firebrick',
    paddingHorizontal: 16,
    alignItems: 'center',
    width: '100%',
    // justifyContent: 'center',
    flexDirection: 'row',
  },
  title: {
    textAlign: 'center',
    color: '#fff',
    marginHorizontal: 16,
    fontWeight: 'bold',
    fontSize: 12,
  },
  // contactLableStyle: {
  //   alignSelf: 'center',
  //   marginVertical: 8,
  //   paddingVertical: 8,
  //   paddingHorizontal: 8,
  //   width: '95%',
  //   fontWeight: 'bold',
  //   backgroundColor: 'firebrick',
  //   color: '#fff',
  // },
  // descriptionStyle: {
  //   width: '95%',
  //   fontWeight: 'bold',
  //   paddingVertical: 8,
  //   alignSelf: 'center',
  //   paddingLeft: 0,
  //   backgroundColor: '#fff',
  //   color: '#000',
  //   borderTopColor: 'gray',
  //   borderTopWidth: 1,
  //   marginTop: 16,
  // },

  titleStyle: {
    // fontWeight: 'bold',
    color: '#000',
    fontSize: 10,
    flex: 1,
    fontSize: 10,
    textAlign: 'center',
  },
  normalText: {
    fontSize: 12,
    textAlign: 'left',
    flex: 2,
  },
  DirectionRow: {
    // flex: 1,
    // backgroundColor: 'red',
    marginVertical: 8,
    flexDirection: 'row',
    borderColor: '#cc0000',
    padding: 4,
    height: 50,
    width: 50,
    borderWidth: 0.5,
    // elevation: 10,
    backgroundColor: '#cc0000',
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBg: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    // marginVertical: 8,
    paddingVertical: 4,
  },
  aboutSellerIconStyle: {
    backgroundColor: '#fff',

    borderWidth: 0,
    elevation: 5,
  },
  headingInModal: {
    borderLeftColor: 'red',
    borderLeftWidth: 2,
    paddingHorizontal: 8,
    marginTop: 20,
    marginBottom: 8,
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
  },
});

export default styles;
