import {
  IMAGES_BASAE_URL,
  FORUM_CATEGORY_SUB_LIST,
  FORUM_CATEGORY,
  JOB_LIST,
  DIRECTORY_CATEGORIES,
  BLOGS_LIST,
  GALLERY_LIST,
  GALLERY_SUB_LIST,
  PROPERTIES,
  NEWS,
  FORUM_COMMENTS,
} from './Urls';

export {
  IMAGES_BASAE_URL,
  FORUM_CATEGORY_SUB_LIST,
  FORUM_CATEGORY,
  JOB_LIST,
  DIRECTORY_CATEGORIES,
  BLOGS_LIST,
  GALLERY_LIST,
  GALLERY_SUB_LIST,
  PROPERTIES,
  NEWS,
  FORUM_COMMENTS,
};
